# networks:
#   rabbitmq:
#     external: true
#     name: rabbitmq_default

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    volumes:
      - ${AppData_Path}:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      - PUID=${UID:-1000}
      - PGID=${PID:-1000}
      - TZ=${TZ}