services:
  mediathekarr:
    image: pcjones/mediathekarr:latest
    container_name: mediathekarr
    environment:
      - PUID=${UID:-1000}
      - PGID=${PID:-1000}
      - TZ=${TZ}
      - DOWNLOAD_FOLDER_PATH_MAPPING=/downloads/completed # Change right side for correct path mapping
      # - MEDIATHEKARR_API_BASE_URL=https://mediathekarr.pcjones.de/api/v1 # Only change this if you are hosting your own API. Not needed for 99% of users
    volumes:
      - "${Data_Dir}/downloads:/app/downloads:rw"      # Change left side to your temp download folder location
    ports:
      - 5007:5007                             # Port can be changed
    restart: unless-stopped