services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:32400 || exit 1"]
    environment:
      - PUID=${UID:-1000}
      - PGID=${PID:-1000}
      - TZ=${TZ}
      - PLEX_CLAIM=${PlexClaim}
      # - PLEX_UID=${PlexUid}
      # - PLEX_GID=${PlexGid}
      # - VERSION=${PlexVersion}
    volumes:
      - "${Config_Dir}/Plex-Media-Server:/config"
      - "${Data_Dir}/data:/data"
      - "${Data_Dir}/data/Transcode:/transcode"
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    restart: unless-stopped
    env_file:
      - path: ./override.env
        required: false
    networks:
      - frontend
      - servarr-network