services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8989 || exit 1"]
    environment:
      - PUID=${UID:-1000}
      - PGID=${PID:-1000}
      - TZ=${TZ}
    volumes:
      - "${AppData_Dir}/Sonarr:/config"
      - "${Data_Dir}/data:/data"
    ports:
      - ${Sonarr_Port_WebUI:-8989}:8989
    env_file:
      - path: ./override.env
        required: false
    restart: unless-stopped
    networks:
      - frontend
      - servarr-network