services:
  azp-build-agent:
    container_name: azp-build-agent-{{.Task.Slot}}
    image: docker.io/internetthingy/azp-agent:alpine-latest
    logging:
      driver: journald
    deploy:
      replicas: 5
    environment:
      - AZP_AGENT_NAME=Alpine - {{.Task.Slot}}
      - AZP_URL=${AZP_URL}
      - AZP_TOKEN=${AZP_TOKEN}
      - AZP_POOL=${AZP_POOL}