services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:6767 || exit 1"]
    environment:
      - PUID=${UID:-1000}
      - PGID=${PID:-1000}
      - TZ=${TZ}
    volumes:
      - "${AppData_Dir}/Bazarr:/config"
      - "${Data_Dir}/data:/data"
    ports:
      - ${Bazarr_Port_WebUI:-6767}:6767
    restart: unless-stopped
    env_file:
      - path: ./override.env
        required: false
    networks:
      - frontend
      - servarr-network